Visual Studio Code (1.88.1, undefined, desktop)
Jupyter Extension Version: 2024.3.1.
Python Extension Version: 2024.4.1.
Pylance Extension Version: 2024.4.1.
Platform: linux (x64).
Workspace folder /opt/smart_farm_network_sim, Home = /home/chandler
14:41:49.224 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher  (Python Path: /bin/python3, Unknown, Python 3.8.10, 3.8.10) for '/opt/smart_farm_network_sim/smart_farm/analysis.ipynb' (disableUI=true)
14:41:49.282 [warn] Failed to get activated env vars for /bin/python3 in 58ms
14:41:49.284 [warn] Failed to get activated env vars for /bin/python3 in 47ms
14:41:49.288 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
14:41:49.306 [error] Unable to determine site packages path for python /bin/python3 (Unknown)
14:41:49.306 [error] Unable to determine site packages path for python /bin/python3 (Unknown)
14:41:49.310 [info] Process Execution: /bin/python3 -m pip list
14:41:49.312 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:41:49.316 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=~/.local/share/jupyter/runtime/kernel-v2-59334Tl8ZEMDlr9q5.json
    > cwd: /opt/smart_farm_network_sim/smart_farm
14:41:49.829 [info] Process Execution: /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2024.3.1-linux-x64/pythonFiles/printJupyterDataDir.py
14:41:56.201 [info] Execution of code ms-toolsai.jupyter-1 completed in 14ms
14:41:56.681 [info] Handle Execution of Cells 6 for /opt/smart_farm_network_sim/smart_farm/analysis.ipynb
14:41:57.263 [warn] Cell completed with errors [hd [Error]: name 'df' is not defined
	at r.execute (~/.vscode/extensions/ms-toolsai.jupyter-2024.3.1-linux-x64/dist/extension.node.js:327:4943)] {
  ename: 'NameError',
  evalue: "name 'df' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[1], line 4\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mmatplotlib\x1B[39;00m\x1B[38;5;21;01m.\x1B[39;00m\x1B[38;5;21;01mpyplot\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mplt\x1B[39;00m\n' +
      '\x1B[1;32m      2\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mnumpy\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mnp\x1B[39;00m\n' +
      "\x1B[0;32m----> 4\x1B[0m pivot_df \x1B[38;5;241m=\x1B[39m \x1B[43mdf\x1B[49m\x1B[38;5;241m.\x1B[39mpivot_table(index\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mmodule\x1B[39m\x1B[38;5;124m'\x1B[39m, columns\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mname\x1B[39m\x1B[38;5;124m'\x1B[39m, values\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mvalue\x1B[39m\x1B[38;5;124m'\x1B[39m, aggfunc\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;124msum\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[1;32m      5\x1B[0m pivot_df\n',
    "\x1B[0;31mNameError\x1B[0m: name 'df' is not defined"
  ]
}
14:41:57.264 [info] Cell 6 completed in 0.577s (start: 1713379316686, end: 1713379317263)
14:42:00.878 [info] Handle Execution of Cells 4 for /opt/smart_farm_network_sim/smart_farm/analysis.ipynb
14:42:01.033 [warn] Cell completed with errors [hd [Error]: name 'results_filepath' is not defined
	at r.execute (~/.vscode/extensions/ms-toolsai.jupyter-2024.3.1-linux-x64/dist/extension.node.js:327:4943)] {
  ename: 'NameError',
  evalue: "name 'results_filepath' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[2], line 3\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mpandas\x1B[39;00m \x1B[38;5;28;01mas\x1B[39;00m \x1B[38;5;21;01mpd\x1B[39;00m\n' +
      "\x1B[0;32m----> 3\x1B[0m csv_file \x1B[38;5;241m=\x1B[39m \x1B[38;5;124mf\x1B[39m\x1B[38;5;124m'\x1B[39m\x1B[38;5;132;01m{\x1B[39;00mresults_filepath\x1B[38;5;132;01m}\x1B[39;00m\x1B[38;5;124m/Results_4-17.csv\x1B[39m\x1B[38;5;124m'\x1B[39m\n" +
      '\x1B[1;32m      4\x1B[0m df \x1B[38;5;241m=\x1B[39m pd\x1B[38;5;241m.\x1B[39mread_csv(csv_file, low_memory\x1B[38;5;241m=\x1B[39m\x1B[38;5;28;01mFalse\x1B[39;00m)\n' +
      "\x1B[1;32m      7\x1B[0m df \x1B[38;5;241m=\x1B[39m df\x1B[38;5;241m.\x1B[39mloc[(df[\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mtype\x1B[39m\x1B[38;5;124m'\x1B[39m] \x1B[38;5;241m==\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mscalar\x1B[39m\x1B[38;5;124m'\x1B[39m), [\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mname\x1B[39m\x1B[38;5;124m'\x1B[39m, \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mmodule\x1B[39m\x1B[38;5;124m'\x1B[39m, \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mvalue\x1B[39m\x1B[38;5;124m'\x1B[39m]]\n",
    "\x1B[0;31mNameError\x1B[0m: name 'results_filepath' is not defined"
  ]
}
14:42:01.034 [info] Cell 4 completed in 0.148s (start: 1713379320885, end: 1713379321033)
14:42:04.283 [info] Handle Execution of Cells 2,4,6 for /opt/smart_farm_network_sim/smart_farm/analysis.ipynb
14:42:04.548 [info] Cell 2 completed in 0.26s (start: 1713379324288, end: 1713379324548)
14:42:04.583 [info] Cell 4 completed in 0.028s (start: 1713379324555, end: 1713379324583)
14:42:04.603 [info] Cell 6 completed in 0.009s (start: 1713379324594, end: 1713379324603)
14:42:06.154 [info] Disposing HostJupyterExecution
14:42:06.154 [info] Dispose Kernel '/opt/smart_farm_network_sim/smart_farm/analysis.ipynb' associated with '/opt/smart_farm_network_sim/smart_farm/analysis.ipynb'
14:42:06.159 [info] Disposing HostJupyterExecution
